#include <stdint.h>
#include "ConfigureRCPSP.h"

namespace ConfigureRCPSP {
	/* TABU LIST SETTINGS */
	TabuType TABU_LIST_TYPE = TABU_LIST;
	uint32_t SIMPLE_TABU_LIST_SIZE = TABU_LIST_SIZE;
	double ADVANCED_TABU_RANDOMIZE_ERASE_AMOUNT = RANDOMIZE_ERASE_AMOUNT;
	uint32_t ADVANCED_TABU_SWAP_LIFE = SWAP_LIFE;
	uint32_t ADVANCED_TABU_SHIFT_LIFE = SHIFT_LIFE;
	/* SCHEDULE SOLVER SETTINGS */
	uint32_t NUMBER_OF_ITERATIONS = DEFAULT_NUMBER_OF_ITERATIONS;
	uint32_t MAXIMAL_NUMBER_OF_ITERATIONS_SINCE_BEST = DEFAULT_MAXIMAL_NUMBER_OF_ITERATIONS_SINCE_BEST;
	uint32_t SWAP_RANGE = DEFAULT_SWAP_RANGE;
	uint32_t SHIFT_RANGE = DEFAULT_SHIFT_RANGE;
	uint32_t DIVERSIFICATION_SWAPS = DEFAULT_DIVERSIFICATION_SWAPS;
}

