#ifndef HLIDAC_PES_CONFIGURE_RCPSP_H
#define HLIDAC_PES_CONFIGURE_RCPSP_H

#include <stdint.h>
#include "ConstantsRCPSP.h"
#include "DefaultConfigureRCPSP.h"

namespace ConfigureRCPSP {
	/* TABU LIST SETTINGS */
	static TabuType TABU_LIST_TYPE = TABU_LIST;
	static uint32_t SIMPLE_TABU_LIST_SIZE = TABU_LIST_SIZE;
	static double ADVANCE_TABU_RANDOMIZE_ERASE_AMOUNT = RANDOMIZE_ERASE_AMOUNT;
	static uint32_t ADVANCE_TABU_SWAP_LIVE = SWAP_LIVE;
	static uint32_t ADVANCE_TABU_SHIFT_LIVE = SHIFT_LIVE;
	/* SCHEDULE SOLVER SETTINGS */
	static uint32_t NUMBER_OF_ITERATIONS = DEFAULT_NUMBER_OF_ITERATIONS;
	static uint32_t MAXIMAL_NUMBER_OF_ITERATIONS_SINCE_BEST = DEFAULT_MAXIMAL_NUMBER_OF_ITERATIONS_SINCE_BEST;
	static uint32_t SWAP_RANGE = DEFAULT_SWAP_RANGE;
	static uint32_t SHIFT_RANGE = DEFAULT_SHIFT_RANGE;
	static uint32_t DIVERSIFICATION_SWAPS = DEFAULT_DIVERSIFICATION_SWAPS;
}

#endif

